# Generated by Django 3.0.7 on 2020-07-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200702_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
