# Generated by Django 3.0.7 on 2020-07-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('home', '0004_customfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cust_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customfields',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='RegisterCust',
        ),
        migrations.DeleteModel(
            name='CustomFields',
        ),
    ]
